/* ============================================================
   TierBrain — shared question repository
   ------------------------------------------------------------
   This file is NOT a page. It is a data library loaded by the
   games via:  <script src="questions.js?v=1"></script>
   Bump the ?v= number whenever you update this file so phones
   fetch the fresh copy instead of a cached one.

   Structure:  TB_BANK[category][tier] = [ {q, correct, wrong:[3]}, ... ]
     - category : "gk" (general knowledge), plus topic banks later
     - tier     : "1" easiest  ->  "4" hardest (matches game levels)

   Use in a game:   var BANK = TB.bank('gk');   // {1:[...],2:[...],3:[...],4:[...]}
   then keep the game's existing question-picking logic.

   CONTENT RULES (keep the bank trustworthy):
     - timeless, verifiable facts only; no current office-holders,
       "latest/biggest", or live records that go stale
     - no disputed answers unless the question is qualified
     - 3 wrong options that are clearly wrong but plausible
   ============================================================ */
(function(){
  var TB_BANK = {
    gk: {
      "1": [
        {q:"Which of these is a number?", correct:"Seven", wrong:["Blue", "Happy", "Round"]},
        {q:"What do you call a baby sheep?", correct:"Lamb", wrong:["Calf", "Foal", "Kitten"]},
        {q:"How many legs does a typical chair have?", correct:"Four", wrong:["Two", "Three", "Six"]},
        {q:"Which of these is a metal?", correct:"Gold", wrong:["Wood", "Plastic", "Paper"]},
        {q:"Which of these flies in the sky?", correct:"Bird", wrong:["Fish", "Snake", "Worm"]},
        {q:"What is the opposite of 'happy'?", correct:"Sad", wrong:["Tall", "Fast", "Loud"]},
        {q:"Which of these is a colour of the rainbow?", correct:"Blue", wrong:["Brown", "Black", "Grey"]},
        {q:"What do you call a person who cooks food in a restaurant?", correct:"Chef", wrong:["Pilot", "Nurse", "Teacher"]},
        {q:"Which farm animal gives us wool?", correct:"Sheep", wrong:["Lion", "Tiger", "Wolf"]},
        {q:"What do we call the meal eaten in the evening?", correct:"Dinner", wrong:["Breakfast", "Lunch", "Brunch"]},
        {q:"Which of these is a fruit, not a vegetable?", correct:"Orange", wrong:["Carrot", "Potato", "Pea"]},
        {q:"How many wings does a typical bird have?", correct:"Two", wrong:["One", "Four", "Six"]},
        {q:"What do you call frozen rain that falls as little balls of ice?", correct:"Hail", wrong:["Snow", "Mist", "Dew"]},
        {q:"Which is heavier: a feather or a brick?", correct:"A brick", wrong:["A feather", "They weigh the same", "Neither"]},
        {q:"What do green plants release into the air that people breathe?", correct:"Oxygen", wrong:["Smoke", "Sand", "Salt"]},
        {q:"Which of these can you ride?", correct:"A bicycle", wrong:["A table", "A lamp", "A book"]},
        {q:"What colour do children most often colour the sun?", correct:"Yellow", wrong:["Blue", "Green", "Purple"]},
        {q:"How many sides does a coin have (heads and tails)?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"What do you call a baby chicken?", correct:"Chick", wrong:["Calf", "Cub", "Joey"]},
        {q:"What do we call the early part of the day when the sun rises?", correct:"Morning", wrong:["Midnight", "Afternoon", "Evening"]},
        {q:"Which of these is used to tell the time?", correct:"A clock", wrong:["A spoon", "A shoe", "A plate"]},
        {q:"What do you call a small house built for a dog?", correct:"A kennel", wrong:["A nest", "A stable", "A web"]},
        {q:"Which animal purrs and is commonly kept as a pet?", correct:"Cat", wrong:["Cow", "Goat", "Horse"]},
        {q:"What is 10 minus 5?", correct:"5", wrong:["4", "6", "15"]},
        {q:"Which of these grows on trees?", correct:"Apples", wrong:["Potatoes", "Carrots", "Fish"]},
        {q:"What do you call a person whose job is to put out fires?", correct:"A firefighter", wrong:["A baker", "A dentist", "A farmer"]},
        {q:"Which is bigger: a kitten or a fully grown cat?", correct:"The grown cat", wrong:["The kitten", "They are the same", "Neither"]},
        {q:"Where do bees live?", correct:"A hive", wrong:["A nest", "A burrow", "A shell"]},
        {q:"How many days are there in a fortnight?", correct:"14", wrong:["7", "10", "30"]},
        {q:"Which of these can you see in the sky at night?", correct:"The Moon", wrong:["The grass", "A car", "A chair"]},
        {q:"What do you call a young human?", correct:"A child", wrong:["An adult", "A senior", "A parent"]},
        {q:"Which of these animals can swim?", correct:"A fish", wrong:["A spider", "A bee", "An ant"]},
        {q:"In which season do leaves often fall from the trees?", correct:"Autumn", wrong:["Summer", "Winter", "Spring"]},
        {q:"How many feet does a person have?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"Which of these is a hot drink?", correct:"Tea", wrong:["Lemonade", "Milkshake", "Cola"]},
        {q:"What do we call the grand home of a king or queen?", correct:"A palace", wrong:["A barn", "A tent", "A cave"]},
        {q:"Which of these is round?", correct:"A ball", wrong:["A box", "A ruler", "A door"]},
        {q:"What is the opposite of 'open'?", correct:"Closed", wrong:["Tall", "Wet", "Loud"]},
        {q:"What is the capital of Japan?", correct:"Tokyo", wrong:["Kyoto", "Osaka", "Beijing"]},
        {q:"How many colours are on a standard traffic light?", correct:"Three", wrong:["Two", "Four", "Five"]},
        {q:"Which animal is known as the 'King of the Jungle'?", correct:"Lion", wrong:["Tiger", "Elephant", "Bear"]},
        {q:"What do you call a baby cow?", correct:"Calf", wrong:["Cub", "Foal", "Kid"]},
        {q:"Which of these is a vegetable?", correct:"Carrot", wrong:["Apple", "Banana", "Cherry"]},
        {q:"How many days are there in a normal (non-leap) year?", correct:"365", wrong:["360", "300", "400"]},
        {q:"What is the opposite of 'big'?", correct:"Small", wrong:["Tall", "Long", "Wide"]},
        {q:"What falls from the sky as soft white flakes in winter?", correct:"Snow", wrong:["Sand", "Ash", "Smoke"]},
        {q:"Which of these shapes is perfectly round?", correct:"Circle", wrong:["Square", "Triangle", "Rectangle"]},
        {q:"What sound does a dog make?", correct:"Bark", wrong:["Meow", "Moo", "Quack"]},
        {q:"How many wheels does a car usually have?", correct:"Four", wrong:["Two", "Three", "Six"]},
        {q:"What is the part of a plant that grows underground called?", correct:"Roots", wrong:["Leaves", "Petals", "Branches"]},
        {q:"Which is fastest: walking, running or crawling?", correct:"Running", wrong:["Walking", "Crawling", "Standing"]},
        {q:"What colour is the inside of a lemon?", correct:"Yellow", wrong:["Blue", "Purple", "Black"]},
        {q:"How many months are there in a year?", correct:"12", wrong:["10", "11", "24"]},
        {q:"Which of these animals lives in water?", correct:"Fish", wrong:["Dog", "Cat", "Horse"]},
        {q:"What do we call the meal eaten in the middle of the day?", correct:"Lunch", wrong:["Breakfast", "Supper", "Snack"]},
        {q:"What colour is fresh snow?", correct:"White", wrong:["Green", "Black", "Orange"]},
        {q:"How many legs does a horse have?", correct:"Four", wrong:["Two", "Six", "Eight"]},
        {q:"Which season is usually the hottest?", correct:"Summer", wrong:["Winter", "Autumn", "Spring"]},
        {q:"What do you call a person who flies a plane?", correct:"Pilot", wrong:["Sailor", "Chef", "Builder"]},
        {q:"Which of these can you drink?", correct:"Water", wrong:["Sand", "Wood", "Glass"]},
        {q:"How many letters are there in the word 'cat'?", correct:"Three", wrong:["Two", "Four", "Five"]},
        {q:"What do cows mainly eat?", correct:"Grass", wrong:["Meat", "Fish", "Insects"]},
        {q:"Which of these is a day of the week?", correct:"Sunday", wrong:["January", "Summer", "Morning"]},
        {q:"What colour are most ripe strawberries?", correct:"Red", wrong:["Blue", "Black", "Yellow"]},
        {q:"How many ears does a typical person have?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"Which animal hops and carries its baby in a pouch?", correct:"Kangaroo", wrong:["Rabbit", "Frog", "Squirrel"]},
        {q:"What do you wear on your feet?", correct:"Shoes", wrong:["Gloves", "A hat", "A scarf"]},
        {q:"What is the opposite of 'day'?", correct:"Night", wrong:["Noon", "Week", "Hour"]},
        {q:"How many thumbs does a typical person have?", correct:"Two", wrong:["One", "Three", "Ten"]},
        {q:"Which of these is a farm animal?", correct:"Pig", wrong:["Lion", "Shark", "Eagle"]},
        {q:"What do you call a group of musicians who play together?", correct:"A band", wrong:["A team", "A flock", "A pack"]},
        {q:"What colour do you get by mixing red and white?", correct:"Pink", wrong:["Green", "Black", "Brown"]},
        {q:"Which of these is used to write on paper?", correct:"A pen", wrong:["A spoon", "A hammer", "A cup"]},
        {q:"What do you call your parents' parents?", correct:"Grandparents", wrong:["Cousins", "Neighbours", "Teachers"]},
        {q:"What is the opposite of 'fast'?", correct:"Slow", wrong:["Tall", "Hot", "Loud"]},
        {q:"Which season has the coldest weather?", correct:"Winter", wrong:["Summer", "Spring", "Autumn"]},
        {q:"How many legs does an insect have?", correct:"Six", wrong:["Four", "Eight", "Ten"]},
        {q:"What is the opposite of 'up'?", correct:"Down", wrong:["Left", "Over", "Around"]},
        {q:"Which fruit is traditionally said to keep the doctor away?", correct:"Apple", wrong:["Banana", "Orange", "Grape"]},
        {q:"What do you call a baby dog?", correct:"Puppy", wrong:["Kitten", "Calf", "Cub"]},
        {q:"How many cents are there in a US dollar?", correct:"100", wrong:["50", "10", "1000"]},
        {q:"Which animal says 'moo'?", correct:"Cow", wrong:["Sheep", "Pig", "Duck"]},
        {q:"How many minutes are there in an hour?", correct:"60", wrong:["30", "100", "24"]},
        {q:"Which is the largest of these numbers: 5, 50 or 500?", correct:"500", wrong:["5", "50", "They are equal"]},
        {q:"What do plants mainly need from the Sun in order to grow?", correct:"Light", wrong:["Sound", "Salt", "Sugar"]},
        {q:"Which of these animals can fly?", correct:"Eagle", wrong:["Penguin", "Ostrich", "Salmon"]},
        {q:"What colour is grass?", correct:"Green", wrong:["Blue", "Red", "Purple"]},
        {q:"How many fingers are on one hand, including the thumb?", correct:"Five", wrong:["Four", "Six", "Ten"]},
        {q:"What do we call the meal usually eaten in the morning?", correct:"Breakfast", wrong:["Dinner", "Supper", "Lunch"]},
        {q:"What do you call a person who teaches pupils at school?", correct:"Teacher", wrong:["Doctor", "Farmer", "Pilot"]},
        {q:"What shape has four equal straight sides?", correct:"Square", wrong:["Triangle", "Circle", "Oval"]},
        {q:"What do bees make?", correct:"Honey", wrong:["Milk", "Silk", "Butter"]},
        {q:"What is the young of a cat called?", correct:"Kitten", wrong:["Puppy", "Foal", "Chick"]},
        {q:"How many sides does a square have?", correct:"Four", wrong:["Three", "Five", "Six"]},
        {q:"Which of these would help you see in the dark?", correct:"A torch", wrong:["A spoon", "A pillow", "A book"]},
        {q:"Which of these is a colour?", correct:"Red", wrong:["Loud", "Fast", "Tall"]},
        {q:"What do you call water that falls from the clouds?", correct:"Rain", wrong:["Sand", "Smoke", "Dust"]},
        {q:"How many eyes does a typical person have?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"What is 2 + 2?", correct:"4", wrong:["3", "5", "22"]},
        {q:"Which animal has a long trunk?", correct:"Elephant", wrong:["Lion", "Zebra", "Bear"]},
        {q:"What day comes immediately after Monday?", correct:"Tuesday", wrong:["Sunday", "Wednesday", "Friday"]},
        {q:"What is the capital of France?", correct:"Paris", wrong:["Lyon","Marseille","Nice"]},
        {q:"How many legs does a spider have?", correct:"Eight", wrong:["Six","Ten","Four"]},
        {q:"What colour do you get by mixing blue and yellow?", correct:"Green", wrong:["Purple","Orange","Brown"]},
        {q:"Which planet do we live on?", correct:"Earth", wrong:["Mars","Venus","Jupiter"]},
        {q:"How many days are there in a week?", correct:"Seven", wrong:["Five","Six","Eight"]},
        {q:"What is H2O more commonly known as?", correct:"Water", wrong:["Salt","Oxygen","Vinegar"]},
        {q:"What is the largest land animal?", correct:"African elephant", wrong:["Hippopotamus","Giraffe","Rhinoceros"]},
        {q:"How many sides does a triangle have?", correct:"Three", wrong:["Four","Five","Two"]},
        {q:"What is the opposite of 'hot'?", correct:"Cold", wrong:["Warm","Dry","Wet"]},
        {q:"Which animal is often called 'man's best friend'?", correct:"Dog", wrong:["Cat","Horse","Rabbit"]},
        {q:"What gas do humans breathe in to survive?", correct:"Oxygen", wrong:["Carbon dioxide","Helium","Hydrogen"]},
        {q:"What is frozen water called?", correct:"Ice", wrong:["Steam","Mist","Fog"]},
        {q:"How many colours are traditionally said to be in a rainbow?", correct:"Seven", wrong:["Five","Six","Nine"]},
        {q:"What is the name of the star at the centre of our solar system?", correct:"The Sun", wrong:["The Moon","Polaris","Mars"]},
        {q:"Which is the tallest living animal in the world?", correct:"Giraffe", wrong:["Elephant","Horse","Camel"]},
        {q:"What do caterpillars turn into?", correct:"Butterflies", wrong:["Spiders","Bees","Beetles"]},
        {q:"What is the first letter of the English alphabet?", correct:"A", wrong:["Z","B","E"]},
        {q:"How many hours are there in a day?", correct:"24", wrong:["12","36","48"]},
        {q:"What colour is a ripe banana?", correct:"Yellow", wrong:["Blue","Purple","Red"]},
        {q:"Which season comes after winter?", correct:"Spring", wrong:["Summer","Autumn","Monsoon"]},
        {q:"What is the capital of England?", correct:"London", wrong:["Manchester","Birmingham","Liverpool"]},
        {q:"How many wheels does a standard bicycle have?", correct:"Two", wrong:["Three","Four","One"]},
        {q:"What do cows produce that people drink?", correct:"Milk", wrong:["Juice","Honey","Cider"]},
        {q:"Which of these is a fruit?", correct:"Apple", wrong:["Carrot","Potato","Onion"]},
        {q:"What is the colour of the sky on a clear day?", correct:"Blue", wrong:["Green","Pink","Grey"]}
      ],
      "2": [
        {q:"What is the capital of Mexico?", correct:"Mexico City", wrong:["Cancun", "Guadalajara", "Tijuana"]},
        {q:"What is the capital of Saudi Arabia?", correct:"Riyadh", wrong:["Jeddah", "Mecca", "Dubai"]},
        {q:"What is the chemical symbol for sulfur?", correct:"S", wrong:["Su", "Sf", "Sl"]},
        {q:"How many sides does an octagon have?", correct:"Eight", wrong:["Six", "Seven", "Ten"]},
        {q:"Who wrote 'Treasure Island'?", correct:"Robert Louis Stevenson", wrong:["Daniel Defoe", "Jules Verne", "Mark Twain"]},
        {q:"Which bird is the fastest, reaching huge speeds in a dive?", correct:"Peregrine falcon", wrong:["Eagle", "Swift", "Albatross"]},
        {q:"What is the currency of India?", correct:"Rupee", wrong:["Yen", "Won", "Ringgit"]},
        {q:"How many players from one team are on the ice in ice hockey?", correct:"Six", wrong:["Five", "Seven", "Eleven"]},
        {q:"What is the capital of the Philippines?", correct:"Manila", wrong:["Cebu", "Davao", "Jakarta"]},
        {q:"How many natural moons does Earth have?", correct:"One", wrong:["Two", "Zero", "Four"]},
        {q:"Who wrote 'The Great Gatsby'?", correct:"F. Scott Fitzgerald", wrong:["Ernest Hemingway", "John Steinbeck", "William Faulkner"]},
        {q:"How many squares are there on a chessboard?", correct:"64", wrong:["32", "48", "100"]},
        {q:"What is the chemical symbol for magnesium?", correct:"Mg", wrong:["Ma", "Mn", "Md"]},
        {q:"Which gas do humans breathe out as a waste product?", correct:"Carbon dioxide", wrong:["Oxygen", "Hydrogen", "Helium"]},
        {q:"Who wrote 'Robinson Crusoe'?", correct:"Daniel Defoe", wrong:["Jonathan Swift", "Jules Verne", "Mark Twain"]},
        {q:"How many cards are there in a standard deck (without jokers)?", correct:"52", wrong:["48", "54", "60"]},
        {q:"What is the capital of Pakistan?", correct:"Islamabad", wrong:["Karachi", "Lahore", "Kabul"]},
        {q:"Which metal is strongly attracted to magnets?", correct:"Iron", wrong:["Gold", "Aluminium", "Copper"]},
        {q:"The three angles of a triangle add up to how many degrees?", correct:"180", wrong:["90", "270", "360"]},
        {q:"Who wrote 'Gulliver's Travels'?", correct:"Jonathan Swift", wrong:["Daniel Defoe", "Lewis Carroll", "Charles Dickens"]},
        {q:"What is the capital of Malaysia?", correct:"Kuala Lumpur", wrong:["Singapore", "Jakarta", "Bangkok"]},
        {q:"Which fairy-tale character leaves behind a glass slipper?", correct:"Cinderella", wrong:["Snow White", "Rapunzel", "Sleeping Beauty"]},
        {q:"How many holes are there on a standard golf course?", correct:"18", wrong:["9", "12", "24"]},
        {q:"What is the capital of Ghana?", correct:"Accra", wrong:["Lagos", "Abuja", "Nairobi"]},
        {q:"In Greek mythology, who had snakes for hair?", correct:"Medusa", wrong:["Athena", "Hera", "Pandora"]},
        {q:"The Wright brothers are famous for inventing what?", correct:"The aeroplane", wrong:["The car", "The telephone", "The light bulb"]},
        {q:"Who wrote 'Black Beauty'?", correct:"Anna Sewell", wrong:["Beatrix Potter", "Louisa May Alcott", "Enid Blyton"]},
        {q:"What is the chemical symbol for phosphorus?", correct:"P", wrong:["Ph", "Po", "Pp"]},
        {q:"What is the capital of Iran?", correct:"Tehran", wrong:["Baghdad", "Riyadh", "Kabul"]},
        {q:"In paint, how many primary colours are there (red, yellow and blue)?", correct:"Three", wrong:["Two", "Four", "Five"]},
        {q:"Who is credited with inventing the telephone?", correct:"Alexander Graham Bell", wrong:["Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"]},
        {q:"How many faces does a cube have?", correct:"Six", wrong:["Four", "Eight", "Twelve"]},
        {q:"What is the capital of Colombia?", correct:"Bogota", wrong:["Medellin", "Cali", "Caracas"]},
        {q:"Which sport is played with a shuttlecock?", correct:"Badminton", wrong:["Tennis", "Squash", "Table tennis"]},
        {q:"In which US city does the Statue of Liberty stand?", correct:"New York City", wrong:["Washington, D.C.", "Boston", "Philadelphia"]},
        {q:"Who wrote 'Peter Pan'?", correct:"J.M. Barrie", wrong:["Lewis Carroll", "Roald Dahl", "A.A. Milne"]},
        {q:"How many wheels does a typical motorcycle have?", correct:"Two", wrong:["Three", "Four", "One"]},
        {q:"Which country is the original home of pizza and pasta?", correct:"Italy", wrong:["France", "Spain", "Greece"]},
        {q:"What is the capital of China?", correct:"Beijing", wrong:["Shanghai", "Hong Kong", "Seoul"]},
        {q:"What is the capital of India?", correct:"New Delhi", wrong:["Mumbai", "Kolkata", "Bangalore"]},
        {q:"What is the chemical symbol for nitrogen?", correct:"N", wrong:["Ni", "Na", "Nt"]},
        {q:"How many planets are there in our solar system?", correct:"8", wrong:["9", "7", "10"]},
        {q:"What is the fastest land animal?", correct:"Cheetah", wrong:["Lion", "Horse", "Greyhound"]},
        {q:"Who wrote 'Charlie and the Chocolate Factory'?", correct:"Roald Dahl", wrong:["Enid Blyton", "C.S. Lewis", "Dr. Seuss"]},
        {q:"What is the main currency of the United States?", correct:"Dollar", wrong:["Peso", "Pound", "Euro"]},
        {q:"How many hearts does an octopus have?", correct:"Three", wrong:["One", "Two", "Eight"]},
        {q:"What is the capital of Brazil?", correct:"Brasilia", wrong:["Rio de Janeiro", "Sao Paulo", "Salvador"]},
        {q:"Which is the largest continent by area?", correct:"Asia", wrong:["Africa", "Europe", "North America"]},
        {q:"How many sides does a pentagon have?", correct:"Five", wrong:["Four", "Six", "Seven"]},
        {q:"What is the study of past events called?", correct:"History", wrong:["Geography", "Biology", "Geology"]},
        {q:"What is the chemical symbol for calcium?", correct:"Ca", wrong:["C", "Cl", "Cm"]},
        {q:"Which planet is often called Earth's 'twin' because of its similar size?", correct:"Venus", wrong:["Mars", "Mercury", "Neptune"]},
        {q:"Who created the detective Sherlock Holmes?", correct:"Arthur Conan Doyle", wrong:["Agatha Christie", "Edgar Allan Poe", "Ian Fleming"]},
        {q:"How many players from one team are on the field in cricket?", correct:"Eleven", wrong:["Nine", "Ten", "Twelve"]},
        {q:"In which country is the Great Wall?", correct:"China", wrong:["Japan", "India", "Mongolia"]},
        {q:"Which element has the chemical symbol 'H'?", correct:"Hydrogen", wrong:["Helium", "Holmium", "Hafnium"]},
        {q:"What is the capital of Kenya?", correct:"Nairobi", wrong:["Mombasa", "Lagos", "Accra"]},
        {q:"How many degrees are there in a right angle?", correct:"90", wrong:["45", "60", "180"]},
        {q:"Who wrote the novel 'Frankenstein'?", correct:"Mary Shelley", wrong:["Bram Stoker", "Jane Austen", "Emily Bronte"]},
        {q:"Which vitamin does the body mainly make when skin is exposed to sunlight?", correct:"Vitamin D", wrong:["Vitamin C", "Vitamin A", "Vitamin B12"]},
        {q:"What is the capital of Argentina?", correct:"Buenos Aires", wrong:["Santiago", "Lima", "Montevideo"]},
        {q:"In which Italian city is the famous Leaning Tower?", correct:"Pisa", wrong:["Rome", "Florence", "Venice"]},
        {q:"In which sport is the Ryder Cup contested?", correct:"Golf", wrong:["Tennis", "Sailing", "Cycling"]},
        {q:"How many zeros are there in the number one thousand?", correct:"3", wrong:["2", "4", "5"]},
        {q:"Who wrote 'The Hobbit'?", correct:"J.R.R. Tolkien", wrong:["C.S. Lewis", "George R.R. Martin", "Roald Dahl"]},
        {q:"What is the chemical symbol for chlorine?", correct:"Cl", wrong:["Ch", "Cr", "Co"]},
        {q:"The statue of Christ the Redeemer overlooks which city?", correct:"Rio de Janeiro", wrong:["Buenos Aires", "Lisbon", "Lima"]},
        {q:"What is the name of the galaxy that contains our solar system?", correct:"The Milky Way", wrong:["Andromeda", "The Solar System", "The Big Dipper"]},
        {q:"Who wrote 'The War of the Worlds'?", correct:"H.G. Wells", wrong:["Jules Verne", "George Orwell", "Arthur C. Clarke"]},
        {q:"How many players from one team are on the field in rugby union?", correct:"Fifteen", wrong:["Thirteen", "Eleven", "Seven"]},
        {q:"What is the capital of Thailand?", correct:"Bangkok", wrong:["Hanoi", "Jakarta", "Manila"]},
        {q:"Which instrument has a keyboard of black and white keys?", correct:"Piano", wrong:["Guitar", "Violin", "Trumpet"]},
        {q:"What is the chemical symbol for zinc?", correct:"Zn", wrong:["Zi", "Zc", "Z"]},
        {q:"What is the shared currency used across much of the European Union?", correct:"Euro", wrong:["Pound", "Franc", "Krona"]},
        {q:"How many lungs does a human have?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"Who wrote 'Alice's Adventures in Wonderland'?", correct:"Lewis Carroll", wrong:["Roald Dahl", "J.M. Barrie", "Beatrix Potter"]},
        {q:"What is the capital of Italy?", correct:"Rome", wrong:["Milan", "Venice", "Naples"]},
        {q:"Who wrote 'A Christmas Carol'?", correct:"Charles Dickens", wrong:["Jane Austen", "Lewis Carroll", "Thomas Hardy"]},
        {q:"What is the chemical symbol for oxygen?", correct:"O", wrong:["Ox", "Og", "Om"]},
        {q:"How many sides does a hexagon have?", correct:"Six", wrong:["Five", "Seven", "Eight"]},
        {q:"Which is the smallest planet in our solar system?", correct:"Mercury", wrong:["Mars", "Venus", "Pluto"]},
        {q:"What is the capital of Germany?", correct:"Berlin", wrong:["Munich", "Hamburg", "Frankfurt"]},
        {q:"In which country are the Pyramids of Giza?", correct:"Egypt", wrong:["Mexico", "Greece", "Sudan"]},
        {q:"What is the currency of the United Kingdom?", correct:"Pound sterling", wrong:["Euro", "Dollar", "Franc"]},
        {q:"Who proposed the theory of evolution by natural selection?", correct:"Charles Darwin", wrong:["Gregor Mendel", "Louis Pasteur", "Carl Linnaeus"]},
        {q:"What is the largest country in the world by area?", correct:"Russia", wrong:["Canada", "China", "United States"]},
        {q:"Which gas do plants absorb from the air for photosynthesis?", correct:"Carbon dioxide", wrong:["Oxygen", "Nitrogen", "Hydrogen"]},
        {q:"What is the highest mountain above sea level on Earth?", correct:"Mount Everest", wrong:["K2", "Mont Blanc", "Kilimanjaro"]},
        {q:"How many bones are there in the adult human body?", correct:"206", wrong:["201", "212", "198"]},
        {q:"What is the capital of Russia?", correct:"Moscow", wrong:["Saint Petersburg", "Kazan", "Minsk"]},
        {q:"Which ocean lies between Africa and Australia?", correct:"Indian Ocean", wrong:["Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"]},
        {q:"What is the boiling point of water at sea level in degrees Celsius?", correct:"100", wrong:["90", "120", "50"]},
        {q:"Who wrote 'The Adventures of Tom Sawyer'?", correct:"Mark Twain", wrong:["Ernest Hemingway", "Jack London", "F. Scott Fitzgerald"]},
        {q:"What is the largest organ of the human body?", correct:"Skin", wrong:["Liver", "Brain", "Lungs"]},
        {q:"How many strings does a standard violin have?", correct:"Four", wrong:["Six", "Five", "Three"]},
        {q:"What is the capital of the United States?", correct:"Washington, D.C.", wrong:["New York City", "Los Angeles", "Chicago"]},
        {q:"Which metal is the best conductor of electricity?", correct:"Silver", wrong:["Copper", "Gold", "Iron"]},
        {q:"Who developed the first widely used polio vaccine in the 1950s?", correct:"Jonas Salk", wrong:["Alexander Fleming", "Edward Jenner", "Robert Koch"]},
        {q:"Which planet is famous for its prominent ring system?", correct:"Saturn", wrong:["Jupiter", "Mars", "Mercury"]},
        {q:"What is the chemical symbol for carbon?", correct:"C", wrong:["Ca", "Co", "Cr"]},
        {q:"How many players from one team are on a basketball court at once?", correct:"Five", wrong:["Six", "Seven", "Four"]},
        {q:"What is the capital of Australia?", correct:"Canberra", wrong:["Sydney","Melbourne","Perth"]},
        {q:"Who wrote the play 'Romeo and Juliet'?", correct:"William Shakespeare", wrong:["Charles Dickens","Jane Austen","Mark Twain"]},
        {q:"What is the chemical symbol for gold?", correct:"Au", wrong:["Gd","Go","Ag"]},
        {q:"How many players from one team are on the pitch in football (soccer)?", correct:"Eleven", wrong:["Ten","Nine","Twelve"]},
        {q:"What is the largest planet in our solar system?", correct:"Jupiter", wrong:["Saturn","Neptune","Earth"]},
        {q:"Which is the largest ocean on Earth?", correct:"Pacific", wrong:["Atlantic","Indian","Arctic"]},
        {q:"What currency is used in Japan?", correct:"Yen", wrong:["Won","Yuan","Ringgit"]},
        {q:"Who painted the Mona Lisa?", correct:"Leonardo da Vinci", wrong:["Michelangelo","Raphael","Donatello"]},
        {q:"What is the hardest known natural substance?", correct:"Diamond", wrong:["Granite","Iron","Quartz"]},
        {q:"How many continents are there on Earth?", correct:"Seven", wrong:["Five","Six","Eight"]},
        {q:"What is the chemical symbol for iron?", correct:"Fe", wrong:["Ir","In","Fr"]},
        {q:"Which gas makes up most of Earth's atmosphere?", correct:"Nitrogen", wrong:["Oxygen","Carbon dioxide","Hydrogen"]},
        {q:"In which country is the Eiffel Tower?", correct:"France", wrong:["Italy","Spain","Belgium"]},
        {q:"What is the smallest prime number?", correct:"2", wrong:["1","3","0"]},
        {q:"Who is the author of the 'Harry Potter' book series?", correct:"J.K. Rowling", wrong:["Roald Dahl","C.S. Lewis","Philip Pullman"]},
        {q:"What is the capital of Canada?", correct:"Ottawa", wrong:["Toronto","Vancouver","Montreal"]},
        {q:"How many strings does a standard guitar have?", correct:"Six", wrong:["Four","Five","Seven"]},
        {q:"What is the freezing point of water in degrees Celsius?", correct:"0", wrong:["32","100","-10"]},
        {q:"Which planet is known as the Red Planet?", correct:"Mars", wrong:["Venus","Mercury","Jupiter"]},
        {q:"What is the official language of Brazil?", correct:"Portuguese", wrong:["Spanish","Brazilian","French"]},
        {q:"Who developed the theory of general relativity?", correct:"Albert Einstein", wrong:["Isaac Newton","Galileo Galilei","Niels Bohr"]},
        {q:"What is the largest mammal in the world?", correct:"Blue whale", wrong:["African elephant","Giraffe","Orca"]},
        {q:"In which sport would you perform a 'slam dunk'?", correct:"Basketball", wrong:["Volleyball","Tennis","Cricket"]},
        {q:"What is the capital of Spain?", correct:"Madrid", wrong:["Barcelona","Seville","Valencia"]},
        {q:"How many minutes are there in a full day?", correct:"1440", wrong:["1240","960","1800"]}
      ],
      "3": [
        {q:"What is the capital of Serbia?", correct:"Belgrade", wrong:["Zagreb", "Sarajevo", "Skopje"]},
        {q:"Who wrote 'Of Mice and Men'?", correct:"John Steinbeck", wrong:["Ernest Hemingway", "F. Scott Fitzgerald", "William Faulkner"]},
        {q:"What is the chemical symbol for aluminium?", correct:"Al", wrong:["Am", "Au", "Ar"]},
        {q:"Which scientist won Nobel Prizes in both Physics and Chemistry for her work on radioactivity?", correct:"Marie Curie", wrong:["Rosalind Franklin", "Lise Meitner", "Dorothy Hodgkin"]},
        {q:"Which art movement is Pablo Picasso credited with co-founding?", correct:"Cubism", wrong:["Surrealism", "Impressionism", "Expressionism"]},
        {q:"What is the capital of Ukraine?", correct:"Kyiv", wrong:["Lviv", "Odesa", "Minsk"]},
        {q:"How many pairs of ribs does a typical human have?", correct:"12", wrong:["10", "14", "8"]},
        {q:"Who wrote 'To Kill a Mockingbird'?", correct:"Harper Lee", wrong:["Toni Morrison", "Maya Angelou", "Truman Capote"]},
        {q:"What is the largest artery in the human body?", correct:"Aorta", wrong:["Vena cava", "Carotid", "Femoral artery"]},
        {q:"Roughly how long does light from the Sun take to reach Earth?", correct:"About 8 minutes", wrong:["About 8 seconds", "About 8 hours", "About 1 minute"]},
        {q:"What is the SI unit of electric current?", correct:"Ampere", wrong:["Volt", "Ohm", "Coulomb"]},
        {q:"What is the capital of Slovakia?", correct:"Bratislava", wrong:["Brno", "Ljubljana", "Vienna"]},
        {q:"What is the process called when liquid water turns into vapour?", correct:"Evaporation", wrong:["Condensation", "Precipitation", "Sublimation"]},
        {q:"Who wrote 'The Picture of Dorian Gray'?", correct:"Oscar Wilde", wrong:["George Bernard Shaw", "Bram Stoker", "Thomas Hardy"]},
        {q:"Rust on iron is mostly made of what?", correct:"Iron oxide", wrong:["Copper sulfate", "Carbon", "Calcium carbonate"]},
        {q:"In which country did the painter Frida Kahlo live and work?", correct:"Mexico", wrong:["Spain", "Argentina", "Colombia"]},
        {q:"What is the capital of Bulgaria?", correct:"Sofia", wrong:["Plovdiv", "Varna", "Bucharest"]},
        {q:"Which blood cells primarily help the body fight infection?", correct:"White blood cells", wrong:["Red blood cells", "Platelets", "Plasma"]},
        {q:"Who wrote the play 'Pygmalion', which inspired 'My Fair Lady'?", correct:"George Bernard Shaw", wrong:["Oscar Wilde", "Noel Coward", "J.B. Priestley"]},
        {q:"What is the capital of Belarus?", correct:"Minsk", wrong:["Kyiv", "Vilnius", "Riga"]},
        {q:"In which year did World War I begin?", correct:"1914", wrong:["1912", "1918", "1939"]},
        {q:"What is the chemical symbol for silicon?", correct:"Si", wrong:["Sc", "Sn", "Sl"]},
        {q:"Which 1215 document limited the power of the English king?", correct:"Magna Carta", wrong:["The Domesday Book", "The Bill of Rights", "The Bayeux Tapestry"]},
        {q:"Who wrote 'Lord of the Flies'?", correct:"William Golding", wrong:["George Orwell", "Aldous Huxley", "J.D. Salinger"]},
        {q:"What is the capital of Lithuania?", correct:"Vilnius", wrong:["Riga", "Tallinn", "Warsaw"]},
        {q:"Which body is the main cause of the ocean tides on Earth?", correct:"The Moon", wrong:["The Sun", "Jupiter", "Mars"]},
        {q:"Who wrote the play 'Death of a Salesman'?", correct:"Arthur Miller", wrong:["Tennessee Williams", "Eugene O'Neill", "Edward Albee"]},
        {q:"What is the central core of an atom called?", correct:"The nucleus", wrong:["The electron", "The proton", "The shell"]},
        {q:"What is the capital of Venezuela?", correct:"Caracas", wrong:["Bogota", "Quito", "Lima"]},
        {q:"Who composed the 'Hungarian Rhapsodies' for piano?", correct:"Franz Liszt", wrong:["Frederic Chopin", "Johannes Brahms", "Robert Schumann"]},
        {q:"Which unit is used to measure the loudness of sound?", correct:"Decibel", wrong:["Hertz", "Watt", "Lumen"]},
        {q:"What is the capital of Nepal?", correct:"Kathmandu", wrong:["Thimphu", "Dhaka", "Lhasa"]},
        {q:"What is the largest muscle in the human body?", correct:"Gluteus maximus", wrong:["Biceps", "Quadriceps", "Deltoid"]},
        {q:"Who wrote the novel 'Catch-22'?", correct:"Joseph Heller", wrong:["Kurt Vonnegut", "Norman Mailer", "John Updike"]},
        {q:"What is the largest species of fish in the world?", correct:"Whale shark", wrong:["Great white shark", "Manta ray", "Marlin"]},
        {q:"What is the capital of Ethiopia?", correct:"Addis Ababa", wrong:["Nairobi", "Khartoum", "Mogadishu"]},
        {q:"Which art movement is Salvador Dali most associated with?", correct:"Surrealism", wrong:["Cubism", "Impressionism", "Pop art"]},
        {q:"What is the SI unit of electric potential (voltage)?", correct:"Volt", wrong:["Ampere", "Ohm", "Watt"]},
        {q:"What is the capital of Austria?", correct:"Vienna", wrong:["Salzburg", "Graz", "Munich"]},
        {q:"Who wrote 'Don Quixote'?", correct:"Miguel de Cervantes", wrong:["Lope de Vega", "Gabriel Garcia Marquez", "Dante Alighieri"]},
        {q:"What is the SI unit of energy?", correct:"Joule", wrong:["Watt", "Newton", "Pascal"]},
        {q:"Which element has the atomic number 6?", correct:"Carbon", wrong:["Nitrogen", "Oxygen", "Boron"]},
        {q:"Which artist is best known for the 'Water Lilies' series and helped found Impressionism?", correct:"Claude Monet", wrong:["Edgar Degas", "Pierre-Auguste Renoir", "Paul Gauguin"]},
        {q:"What is the capital of the Netherlands?", correct:"Amsterdam", wrong:["The Hague", "Rotterdam", "Utrecht"]},
        {q:"How many chambers does the human heart have?", correct:"Four", wrong:["Two", "Three", "Six"]},
        {q:"In which museum does the Mona Lisa hang?", correct:"The Louvre", wrong:["The Uffizi", "The Prado", "The Met"]},
        {q:"Who wrote 'Les Miserables'?", correct:"Victor Hugo", wrong:["Alexandre Dumas", "Emile Zola", "Gustave Flaubert"]},
        {q:"Which planet has the strongest surface gravity?", correct:"Jupiter", wrong:["Saturn", "Earth", "Neptune"]},
        {q:"What is the SI unit of power?", correct:"Watt", wrong:["Joule", "Newton", "Hertz"]},
        {q:"What is the capital of Poland?", correct:"Warsaw", wrong:["Krakow", "Gdansk", "Lodz"]},
        {q:"What is the process by which green plants make their own food?", correct:"Photosynthesis", wrong:["Respiration", "Digestion", "Fermentation"]},
        {q:"Who wrote 'Wuthering Heights'?", correct:"Emily Bronte", wrong:["Charlotte Bronte", "Jane Austen", "Mary Shelley"]},
        {q:"What is the largest island in the world?", correct:"Greenland", wrong:["New Guinea", "Madagascar", "Borneo"]},
        {q:"Who painted 'The Scream'?", correct:"Edvard Munch", wrong:["Gustav Klimt", "Egon Schiele", "Edward Hopper"]},
        {q:"What is the capital of Hungary?", correct:"Budapest", wrong:["Vienna", "Belgrade", "Bucharest"]},
        {q:"Sound travels fastest through which of these?", correct:"Steel", wrong:["Air", "Water", "A vacuum"]},
        {q:"Which scientist is credited with creating the periodic table of elements?", correct:"Dmitri Mendeleev", wrong:["Marie Curie", "John Dalton", "Antoine Lavoisier"]},
        {q:"Who wrote the novel 'Dracula'?", correct:"Bram Stoker", wrong:["Mary Shelley", "Edgar Allan Poe", "H.P. Lovecraft"]},
        {q:"What is the capital of the Czech Republic?", correct:"Prague", wrong:["Brno", "Vienna", "Bratislava"]},
        {q:"Which blood vessels carry blood away from the heart?", correct:"Arteries", wrong:["Veins", "Capillaries", "Nerves"]},
        {q:"In which city is the Acropolis?", correct:"Athens", wrong:["Rome", "Cairo", "Istanbul"]},
        {q:"Who is traditionally credited as the author of 'The Odyssey'?", correct:"Homer", wrong:["Virgil", "Sophocles", "Ovid"]},
        {q:"What is the SI unit of pressure?", correct:"Pascal", wrong:["Newton", "Joule", "Bar"]},
        {q:"What is the capital of Chile?", correct:"Santiago", wrong:["Valparaiso", "Lima", "Bogota"]},
        {q:"Roughly what percentage of Earth's atmosphere is oxygen?", correct:"21%", wrong:["50%", "78%", "10%"]},
        {q:"Which artist is famous for pop-art images of soup cans?", correct:"Andy Warhol", wrong:["Roy Lichtenstein", "Jackson Pollock", "Jasper Johns"]},
        {q:"What is the capital of Vietnam?", correct:"Hanoi", wrong:["Ho Chi Minh City", "Hue", "Da Nang"]},
        {q:"In which part of the body is the smallest human bone found?", correct:"The ear", wrong:["The nose", "The hand", "The foot"]},
        {q:"Who wrote 'The Count of Monte Cristo'?", correct:"Alexandre Dumas", wrong:["Victor Hugo", "Jules Verne", "Honore de Balzac"]},
        {q:"In which year did humans first land on the Moon?", correct:"1969", wrong:["1965", "1972", "1959"]},
        {q:"What is the capital of South Korea?", correct:"Seoul", wrong:["Busan", "Pyongyang", "Incheon"]},
        {q:"Who wrote 'Jane Eyre'?", correct:"Charlotte Bronte", wrong:["Emily Bronte", "Anne Bronte", "Elizabeth Gaskell"]},
        {q:"Which natural events are measured on the Richter scale?", correct:"Earthquakes", wrong:["Wind speed", "Rainfall", "Temperature"]},
        {q:"What is the capital of Belgium?", correct:"Brussels", wrong:["Antwerp", "Bruges", "Ghent"]},
        {q:"Which is the smallest and shallowest of the world's oceans?", correct:"Arctic Ocean", wrong:["Indian Ocean", "Southern Ocean", "Atlantic Ocean"]},
        {q:"How many degrees are there in a full circle?", correct:"360", wrong:["180", "270", "400"]},
        {q:"What is the capital of Greece?", correct:"Athens", wrong:["Thessaloniki", "Sparta", "Corinth"]},
        {q:"Who wrote 'Pride and Prejudice'?", correct:"Jane Austen", wrong:["Charlotte Bronte", "Emily Bronte", "George Eliot"]},
        {q:"What is the SI unit of force?", correct:"Newton", wrong:["Joule", "Pascal", "Watt"]},
        {q:"Which element has the chemical symbol 'Cu'?", correct:"Copper", wrong:["Calcium", "Cobalt", "Chromium"]},
        {q:"Who wrote the play 'A Doll's House'?", correct:"Henrik Ibsen", wrong:["Anton Chekhov", "August Strindberg", "Oscar Wilde"]},
        {q:"What is the name of the giant storm on Jupiter?", correct:"The Great Red Spot", wrong:["The Cassini Division", "The Great Dark Spot", "Olympus Mons"]},
        {q:"In what year did the Titanic sink?", correct:"1912", wrong:["1905", "1918", "1920"]},
        {q:"What is the capital of Portugal?", correct:"Lisbon", wrong:["Porto", "Coimbra", "Faro"]},
        {q:"What is the chemical formula for common table salt?", correct:"NaCl", wrong:["KCl", "NaCO", "Na2O"]},
        {q:"Who painted 'Guernica'?", correct:"Pablo Picasso", wrong:["Salvador Dali", "Joan Miro", "Francisco Goya"]},
        {q:"Which planet has the hottest surface in our solar system?", correct:"Venus", wrong:["Mercury", "Mars", "Jupiter"]},
        {q:"What is the scientific study of living organisms called?", correct:"Biology", wrong:["Geology", "Chemistry", "Physics"]},
        {q:"Which ancient Greek philosopher tutored Alexander the Great?", correct:"Aristotle", wrong:["Plato", "Socrates", "Pythagoras"]},
        {q:"What is the capital of Sweden?", correct:"Stockholm", wrong:["Gothenburg", "Malmo", "Helsinki"]},
        {q:"Which blood type is known as the universal donor?", correct:"O negative", wrong:["AB positive", "A positive", "B negative"]},
        {q:"Who wrote the novel 'Moby-Dick'?", correct:"Herman Melville", wrong:["Nathaniel Hawthorne", "Edgar Allan Poe", "Walt Whitman"]},
        {q:"What is the smallest unit of an element that keeps its properties?", correct:"Atom", wrong:["Molecule", "Cell", "Proton"]},
        {q:"In Roman numerals, what number does 'L' represent?", correct:"50", wrong:["100", "500", "5"]},
        {q:"What is the capital of Ireland?", correct:"Dublin", wrong:["Belfast", "Cork", "Galway"]},
        {q:"Which scientist is traditionally said to have been inspired by a falling apple?", correct:"Isaac Newton", wrong:["Galileo Galilei", "Albert Einstein", "Robert Hooke"]},
        {q:"What is the chemical symbol for silver?", correct:"Ag", wrong:["Si", "Sv", "Sl"]},
        {q:"Which sea lies between Europe and Africa, narrowest at the Strait of Gibraltar?", correct:"Mediterranean Sea", wrong:["Black Sea", "Red Sea", "Caspian Sea"]},
        {q:"Who wrote 'The Old Man and the Sea'?", correct:"Ernest Hemingway", wrong:["John Steinbeck", "William Faulkner", "F. Scott Fitzgerald"]},
        {q:"Which part of a cell is often called its 'powerhouse'?", correct:"Mitochondria", wrong:["Nucleus", "Ribosome", "Golgi apparatus"]},
        {q:"Which country gave the Statue of Liberty to the United States?", correct:"France", wrong:["United Kingdom", "Spain", "Italy"]},
        {q:"What is the SI unit of electrical resistance?", correct:"Ohm", wrong:["Volt","Ampere","Watt"]},
        {q:"Who wrote the novel 'Crime and Punishment'?", correct:"Fyodor Dostoevsky", wrong:["Leo Tolstoy","Anton Chekhov","Ivan Turgenev"]},
        {q:"What is the capital of New Zealand?", correct:"Wellington", wrong:["Auckland","Christchurch","Hamilton"]},
        {q:"Which element has the atomic number 1?", correct:"Hydrogen", wrong:["Helium","Oxygen","Carbon"]},
        {q:"Who composed 'The Four Seasons'?", correct:"Antonio Vivaldi", wrong:["Johann Sebastian Bach","Wolfgang Amadeus Mozart","Ludwig van Beethoven"]},
        {q:"What is the world's largest hot desert?", correct:"Sahara", wrong:["Gobi","Kalahari","Arabian"]},
        {q:"In Greek mythology, who is the king of the gods?", correct:"Zeus", wrong:["Poseidon","Hades","Apollo"]},
        {q:"What is the chemical symbol for sodium?", correct:"Na", wrong:["So","Sd","S"]},
        {q:"Which artist famously cut off part of his own ear?", correct:"Vincent van Gogh", wrong:["Pablo Picasso","Claude Monet","Salvador Dali"]},
        {q:"Which organ in the human body produces insulin?", correct:"Pancreas", wrong:["Liver","Kidney","Spleen"]},
        {q:"Who was the first person to walk on the Moon?", correct:"Neil Armstrong", wrong:["Buzz Aldrin","Yuri Gagarin","Michael Collins"]},
        {q:"What is the capital of Egypt?", correct:"Cairo", wrong:["Alexandria","Giza","Luxor"]},
        {q:"In which Shakespeare play does the character Iago appear?", correct:"Othello", wrong:["Hamlet","Macbeth","King Lear"]},
        {q:"The speed of light in a vacuum is approximately how fast?", correct:"300,000 km/s", wrong:["150,000 km/s","30,000 km/s","3,000 km/s"]},
        {q:"Who composed the music for the ballet 'Swan Lake'?", correct:"Pyotr Ilyich Tchaikovsky", wrong:["Igor Stravinsky","Sergei Prokofiev","Claude Debussy"]},
        {q:"What is the largest internal organ in the human body?", correct:"Liver", wrong:["Stomach","Lungs","Brain"]},
        {q:"Which metal is liquid at room temperature?", correct:"Mercury", wrong:["Lead","Aluminium","Zinc"]},
        {q:"What is the capital of Norway?", correct:"Oslo", wrong:["Bergen","Stavanger","Trondheim"]},
        {q:"Who painted 'The Persistence of Memory', known for its melting clocks?", correct:"Salvador Dali", wrong:["Pablo Picasso","Joan Miro","Rene Magritte"]},
        {q:"What is the longest bone in the human body?", correct:"Femur", wrong:["Tibia","Humerus","Fibula"]},
        {q:"In which year did World War II end?", correct:"1945", wrong:["1944","1946","1939"]},
        {q:"What is the chemical symbol for potassium?", correct:"K", wrong:["P","Po","Pt"]},
        {q:"Which planet is closest to the Sun?", correct:"Mercury", wrong:["Venus","Earth","Mars"]},
        {q:"Who wrote the novels '1984' and 'Animal Farm'?", correct:"George Orwell", wrong:["Aldous Huxley","Ray Bradbury","H.G. Wells"]},
        {q:"What is the scientific study of weather called?", correct:"Meteorology", wrong:["Geology","Astrology","Ecology"]}
      ],
      "4": [
        {q:"What is the capital of Slovenia?", correct:"Ljubljana", wrong:["Zagreb", "Bratislava", "Vienna"]},
        {q:"Who wrote 'Doctor Zhivago'?", correct:"Boris Pasternak", wrong:["Mikhail Bulgakov", "Vladimir Nabokov", "Aleksandr Solzhenitsyn"]},
        {q:"Which element has the atomic number 26?", correct:"Iron", wrong:["Copper", "Nickel", "Zinc"]},
        {q:"Who composed the 'William Tell Overture'?", correct:"Gioachino Rossini", wrong:["Giuseppe Verdi", "Gaetano Donizetti", "Vincenzo Bellini"]},
        {q:"Who painted 'The Garden of Earthly Delights'?", correct:"Hieronymus Bosch", wrong:["Pieter Bruegel", "Jan van Eyck", "Albrecht Durer"]},
        {q:"Which philosopher is famous for the statement 'I think, therefore I am'?", correct:"Rene Descartes", wrong:["Baruch Spinoza", "John Locke", "David Hume"]},
        {q:"What is the capital of Estonia?", correct:"Tallinn", wrong:["Riga", "Vilnius", "Helsinki"]},
        {q:"Which element has the chemical symbol 'U'?", correct:"Uranium", wrong:["Thorium", "Plutonium", "Radium"]},
        {q:"Who wrote the novella 'Heart of Darkness'?", correct:"Joseph Conrad", wrong:["Rudyard Kipling", "E.M. Forster", "Thomas Hardy"]},
        {q:"Which scientist pioneered the smallpox vaccine?", correct:"Edward Jenner", wrong:["Louis Pasteur", "Jonas Salk", "Robert Koch"]},
        {q:"Who sculpted the Baroque masterpiece 'Ecstasy of Saint Teresa'?", correct:"Gian Lorenzo Bernini", wrong:["Michelangelo", "Donatello", "Caravaggio"]},
        {q:"What is the capital of Latvia?", correct:"Riga", wrong:["Tallinn", "Vilnius", "Minsk"]},
        {q:"Which element, essential to the thyroid, has the symbol 'I'?", correct:"Iodine", wrong:["Indium", "Iridium", "Iron"]},
        {q:"Who wrote 'The Sound and the Fury'?", correct:"William Faulkner", wrong:["Ernest Hemingway", "John Steinbeck", "F. Scott Fitzgerald"]},
        {q:"Who composed the opera 'Aida'?", correct:"Giuseppe Verdi", wrong:["Giacomo Puccini", "Gioachino Rossini", "Vincenzo Bellini"]},
        {q:"What is the capital of Lebanon?", correct:"Beirut", wrong:["Damascus", "Amman", "Cairo"]},
        {q:"Which ancient Greek mathematician is said to have shouted 'Eureka!' in his bath?", correct:"Archimedes", wrong:["Pythagoras", "Euclid", "Thales"]},
        {q:"Who painted the work popularly known as 'Whistler's Mother'?", correct:"James McNeill Whistler", wrong:["John Singer Sargent", "Thomas Eakins", "Winslow Homer"]},
        {q:"What is the capital of Jordan?", correct:"Amman", wrong:["Beirut", "Damascus", "Baghdad"]},
        {q:"What is the largest moon in our solar system?", correct:"Ganymede", wrong:["Titan", "Callisto", "The Moon"]},
        {q:"Who wrote the Nobel Prize-winning novel 'Beloved'?", correct:"Toni Morrison", wrong:["Maya Angelou", "Alice Walker", "Zora Neale Hurston"]},
        {q:"What is the SI base unit of temperature?", correct:"Kelvin", wrong:["Celsius", "Fahrenheit", "Joule"]},
        {q:"What is the capital of Syria?", correct:"Damascus", wrong:["Beirut", "Amman", "Baghdad"]},
        {q:"Who composed the 'Peer Gynt' suite, including 'In the Hall of the Mountain King'?", correct:"Edvard Grieg", wrong:["Jean Sibelius", "Carl Nielsen", "Antonin Dvorak"]},
        {q:"Which naturalist independently conceived the theory of natural selection alongside Darwin?", correct:"Alfred Russel Wallace", wrong:["Thomas Huxley", "Herbert Spencer", "Gregor Mendel"]},
        {q:"What is the capital of Algeria?", correct:"Algiers", wrong:["Tunis", "Tripoli", "Rabat"]},
        {q:"Who wrote the epic poem 'The Faerie Queene'?", correct:"Edmund Spenser", wrong:["John Milton", "Geoffrey Chaucer", "Andrew Marvell"]},
        {q:"Which subatomic particle carries a negative electric charge?", correct:"Electron", wrong:["Proton", "Neutron", "Positron"]},
        {q:"Who painted the English landscape 'The Hay Wain'?", correct:"John Constable", wrong:["J.M.W. Turner", "Thomas Gainsborough", "George Stubbs"]},
        {q:"What is the capital of Tunisia?", correct:"Tunis", wrong:["Tripoli", "Algiers", "Cairo"]},
        {q:"Who composed the 'New World Symphony'?", correct:"Antonin Dvorak", wrong:["Bedrich Smetana", "Leos Janacek", "Gustav Mahler"]},
        {q:"What is the scientific study of the origin and structure of the universe called?", correct:"Cosmology", wrong:["Geology", "Meteorology", "Ecology"]},
        {q:"Who wrote the novel 'The Stranger' (L'Etranger)?", correct:"Albert Camus", wrong:["Jean-Paul Sartre", "Andre Malraux", "Simone de Beauvoir"]},
        {q:"In which year did the Wright brothers make their first powered flight?", correct:"1903", wrong:["1899", "1912", "1920"]},
        {q:"Who painted 'Nighthawks', the late-night diner scene?", correct:"Edward Hopper", wrong:["Grant Wood", "Norman Rockwell", "Andrew Wyeth"]},
        {q:"Which philosopher wrote 'Thus Spoke Zarathustra'?", correct:"Friedrich Nietzsche", wrong:["Arthur Schopenhauer", "Soren Kierkegaard", "Martin Heidegger"]},
        {q:"What is the capital of Switzerland?", correct:"Bern", wrong:["Zurich", "Geneva", "Basel"]},
        {q:"Who wrote 'The Metamorphosis'?", correct:"Franz Kafka", wrong:["Hermann Hesse", "Thomas Mann", "Bertolt Brecht"]},
        {q:"Which element has the atomic number 79?", correct:"Gold", wrong:["Silver", "Platinum", "Mercury"]},
        {q:"Who composed the oratorio 'Messiah', including the 'Hallelujah' chorus?", correct:"George Frideric Handel", wrong:["Johann Sebastian Bach", "Antonio Vivaldi", "Henry Purcell"]},
        {q:"Who painted 'The Kiss' (1908), famous for its gold leaf?", correct:"Gustav Klimt", wrong:["Egon Schiele", "Oskar Kokoschka", "Edvard Munch"]},
        {q:"Which philosopher wrote 'The Republic'?", correct:"Plato", wrong:["Aristotle", "Socrates", "Epicurus"]},
        {q:"What is the capital of Croatia?", correct:"Zagreb", wrong:["Split", "Belgrade", "Ljubljana"]},
        {q:"Which element has the chemical symbol 'Ne'?", correct:"Neon", wrong:["Nickel", "Nitrogen", "Neptunium"]},
        {q:"Who wrote the play 'Waiting for Godot'?", correct:"Samuel Beckett", wrong:["Eugene Ionesco", "Harold Pinter", "Tom Stoppard"]},
        {q:"Which scientist proposed the theory of continental drift?", correct:"Alfred Wegener", wrong:["Charles Lyell", "James Hutton", "Charles Darwin"]},
        {q:"Who sculpted 'The Thinker'?", correct:"Auguste Rodin", wrong:["Antonio Canova", "Donatello", "Henry Moore"]},
        {q:"What is the capital of Denmark?", correct:"Copenhagen", wrong:["Aarhus", "Bergen", "Malmo"]},
        {q:"Which is the second most abundant element in the universe?", correct:"Helium", wrong:["Oxygen", "Carbon", "Nitrogen"]},
        {q:"Who wrote the novel 'Ulysses'?", correct:"James Joyce", wrong:["Virginia Woolf", "D.H. Lawrence", "T.S. Eliot"]},
        {q:"Who composed the opera 'Carmen'?", correct:"Georges Bizet", wrong:["Giacomo Puccini", "Giuseppe Verdi", "Charles Gounod"]},
        {q:"What is the capital of Turkey?", correct:"Ankara", wrong:["Istanbul", "Izmir", "Bursa"]},
        {q:"What is the value of pi to two decimal places?", correct:"3.14", wrong:["3.41", "3.12", "3.16"]},
        {q:"Who painted 'Girl with a Pearl Earring'?", correct:"Johannes Vermeer", wrong:["Rembrandt", "Frans Hals", "Jan Steen"]},
        {q:"What is the capital of Iraq?", correct:"Baghdad", wrong:["Basra", "Mosul", "Tehran"]},
        {q:"Which planet, discovered in 1846, was the first found by mathematical prediction?", correct:"Neptune", wrong:["Uranus", "Pluto", "Saturn"]},
        {q:"Who wrote 'In Search of Lost Time'?", correct:"Marcel Proust", wrong:["Albert Camus", "Jean-Paul Sartre", "Andre Gide"]},
        {q:"What is the SI base unit for the amount of a substance?", correct:"Mole", wrong:["Candela", "Kelvin", "Ampere"]},
        {q:"What is the capital of Nigeria?", correct:"Abuja", wrong:["Lagos", "Kano", "Ibadan"]},
        {q:"Who composed 'Bolero'?", correct:"Maurice Ravel", wrong:["Claude Debussy", "Erik Satie", "Camille Saint-Saens"]},
        {q:"Who is often regarded as the first computer programmer, for her work on Babbage's Analytical Engine?", correct:"Ada Lovelace", wrong:["Grace Hopper", "Alan Turing", "Charles Babbage"]},
        {q:"What is the capital of Peru?", correct:"Lima", wrong:["Cusco", "Arequipa", "Quito"]},
        {q:"Who wrote the epic poem 'Paradise Lost'?", correct:"John Milton", wrong:["Geoffrey Chaucer", "Edmund Spenser", "John Donne"]},
        {q:"Which scientist discovered the laws of inheritance using pea plants?", correct:"Gregor Mendel", wrong:["Charles Darwin", "Louis Pasteur", "Thomas Morgan"]},
        {q:"Who painted 'American Gothic'?", correct:"Grant Wood", wrong:["Edward Hopper", "Norman Rockwell", "Andrew Wyeth"]},
        {q:"What is the capital of Cuba?", correct:"Havana", wrong:["Santiago de Cuba", "Kingston", "Santo Domingo"]},
        {q:"Who composed the orchestral suite 'The Planets'?", correct:"Gustav Holst", wrong:["Edward Elgar", "Ralph Vaughan Williams", "Benjamin Britten"]},
        {q:"Which planet has the longest day (the longest rotation period)?", correct:"Venus", wrong:["Mercury", "Mars", "Neptune"]},
        {q:"Who wrote 'Madame Bovary'?", correct:"Gustave Flaubert", wrong:["Honore de Balzac", "Stendhal", "Emile Zola"]},
        {q:"What is the capital of Romania?", correct:"Bucharest", wrong:["Cluj-Napoca", "Sofia", "Belgrade"]},
        {q:"Who painted 'Las Meninas'?", correct:"Diego Velazquez", wrong:["Francisco Goya", "El Greco", "Bartolome Murillo"]},
        {q:"What is the scientific study of fungi called?", correct:"Mycology", wrong:["Botany", "Zoology", "Entomology"]},
        {q:"Who wrote 'One Hundred Years of Solitude'?", correct:"Gabriel Garcia Marquez", wrong:["Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"]},
        {q:"What is the chemical symbol for the element mercury?", correct:"Hg", wrong:["Mc", "Me", "Mg"]},
        {q:"Which ancient Greek is known as the 'father of geometry'?", correct:"Euclid", wrong:["Pythagoras", "Archimedes", "Thales"]},
        {q:"What is the capital of Finland?", correct:"Helsinki", wrong:["Stockholm", "Oslo", "Tallinn"]},
        {q:"Who composed 'The Rite of Spring'?", correct:"Igor Stravinsky", wrong:["Claude Debussy", "Maurice Ravel", "Sergei Rachmaninoff"]},
        {q:"What is the most abundant metal in the Earth's crust?", correct:"Aluminium", wrong:["Iron", "Copper", "Magnesium"]},
        {q:"Who painted 'The Night Watch'?", correct:"Rembrandt", wrong:["Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"]},
        {q:"What is the term for an animal that eats only plants?", correct:"Herbivore", wrong:["Carnivore", "Omnivore", "Insectivore"]},
        {q:"Which civilization built the mountain city of Machu Picchu?", correct:"The Inca", wrong:["The Aztec", "The Maya", "The Olmec"]},
        {q:"What is the chemical symbol for tin?", correct:"Sn", wrong:["Ti", "Tn", "Te"]},
        {q:"Who wrote the dystopian novel 'Brave New World'?", correct:"Aldous Huxley", wrong:["George Orwell", "Ray Bradbury", "Yevgeny Zamyatin"]},
        {q:"What is the SI unit of frequency?", correct:"Hertz", wrong:["Decibel", "Joule", "Pascal"]},
        {q:"Which lake is so salty that swimmers float easily in it?", correct:"The Dead Sea", wrong:["The Red Sea", "The Caspian Sea", "Lake Victoria"]},
        {q:"Who founded the practice of psychoanalysis?", correct:"Sigmund Freud", wrong:["Carl Jung", "Ivan Pavlov", "B.F. Skinner"]},
        {q:"What is the capital of Iceland?", correct:"Reykjavik", wrong:["Oslo", "Nuuk", "Bergen"]},
        {q:"Which element is represented by the symbol 'He'?", correct:"Helium", wrong:["Hydrogen", "Mercury", "Hafnium"]},
        {q:"Who wrote the two-part tragedy 'Faust'?", correct:"Johann Wolfgang von Goethe", wrong:["Friedrich Schiller", "Heinrich Heine", "Thomas Mann"]},
        {q:"What is the hardest substance produced by the human body?", correct:"Tooth enamel", wrong:["Bone", "Cartilage", "Fingernail"]},
        {q:"Who composed the 'Brandenburg Concertos'?", correct:"Johann Sebastian Bach", wrong:["George Frideric Handel", "Antonio Vivaldi", "Henry Purcell"]},
        {q:"What is the largest moon of the planet Saturn?", correct:"Titan", wrong:["Europa", "Ganymede", "Triton"]},
        {q:"Who wrote 'The Canterbury Tales'?", correct:"Geoffrey Chaucer", wrong:["William Langland", "Thomas Malory", "John Gower"]},
        {q:"Which gas, with the formula O3, forms a protective layer in the stratosphere?", correct:"Ozone", wrong:["Carbon monoxide", "Methane", "Argon"]},
        {q:"What is the capital of Morocco?", correct:"Rabat", wrong:["Casablanca", "Marrakech", "Fez"]},
        {q:"Who painted 'The Birth of Venus'?", correct:"Sandro Botticelli", wrong:["Titian", "Raphael", "Caravaggio"]},
        {q:"In physics, the letter 'c' most commonly represents what?", correct:"The speed of light", wrong:["Acceleration", "Mass", "Electric charge"]},
        {q:"Who proposed the uncertainty principle in quantum mechanics?", correct:"Werner Heisenberg", wrong:["Erwin Schrodinger","Max Planck","Paul Dirac"]},
        {q:"What is the capital of Bhutan?", correct:"Thimphu", wrong:["Kathmandu","Dhaka","Naypyidaw"]},
        {q:"Which Russian author wrote 'War and Peace'?", correct:"Leo Tolstoy", wrong:["Fyodor Dostoevsky","Boris Pasternak","Maxim Gorky"]},
        {q:"What is the chemical symbol for tungsten?", correct:"W", wrong:["Tu","Tn","Tg"]},
        {q:"In what year did the Berlin Wall fall?", correct:"1989", wrong:["1987","1991","1985"]},
        {q:"Who composed the opera 'The Marriage of Figaro'?", correct:"Wolfgang Amadeus Mozart", wrong:["Giuseppe Verdi","Richard Wagner","Giacomo Puccini"]},
        {q:"What is the smallest country in the world by area?", correct:"Vatican City", wrong:["Monaco","San Marino","Liechtenstein"]},
        {q:"Which scientist formulated the three laws of planetary motion?", correct:"Johannes Kepler", wrong:["Tycho Brahe","Galileo Galilei","Nicolaus Copernicus"]},
        {q:"Which mineral sits at the top (10) of the Mohs hardness scale?", correct:"Diamond", wrong:["Corundum","Topaz","Quartz"]},
        {q:"Who wrote the philosophical work 'Critique of Pure Reason'?", correct:"Immanuel Kant", wrong:["Friedrich Nietzsche","Georg Hegel","Arthur Schopenhauer"]},
        {q:"What is the capital of Mongolia?", correct:"Ulaanbaatar", wrong:["Astana","Bishkek","Tashkent"]},
        {q:"Which metal has the highest melting point?", correct:"Tungsten", wrong:["Iron","Platinum","Titanium"]},
        {q:"Who painted the ceiling of the Sistine Chapel?", correct:"Michelangelo", wrong:["Leonardo da Vinci","Raphael","Caravaggio"]},
        {q:"What is the longest river in South America?", correct:"Amazon", wrong:["Parana","Orinoco","Sao Francisco"]},
        {q:"Which mathematician is known for his 'Last Theorem'?", correct:"Pierre de Fermat", wrong:["Carl Gauss","Leonhard Euler","Blaise Pascal"]},
        {q:"What is the chemical symbol for lead?", correct:"Pb", wrong:["Ld","Le","Pl"]},
        {q:"Which Ancient Wonder stood in the harbour of Rhodes?", correct:"The Colossus of Rhodes", wrong:["The Hanging Gardens","The Lighthouse of Alexandria","The Temple of Artemis"]},
        {q:"Who wrote the epic poem 'The Divine Comedy'?", correct:"Dante Alighieri", wrong:["Petrarch","Giovanni Boccaccio","Virgil"]},
        {q:"What is the SI base unit of luminous intensity?", correct:"Candela", wrong:["Lumen","Lux","Watt"]},
        {q:"Which composer kept composing after becoming profoundly deaf?", correct:"Ludwig van Beethoven", wrong:["Franz Schubert","Johannes Brahms","Frederic Chopin"]},
        {q:"Which planet in our solar system rotates roughly on its side?", correct:"Uranus", wrong:["Neptune","Saturn","Venus"]},
        {q:"Who is credited with discovering penicillin?", correct:"Alexander Fleming", wrong:["Louis Pasteur","Joseph Lister","Robert Koch"]},
        {q:"What is the term for a word that reads the same forwards and backwards?", correct:"Palindrome", wrong:["Anagram","Homonym","Onomatopoeia"]},
        {q:"Which element is the most abundant in the Sun?", correct:"Hydrogen", wrong:["Helium","Oxygen","Carbon"]},
        {q:"In Greek mythology, who flew too close to the Sun on wax wings?", correct:"Icarus", wrong:["Daedalus","Perseus","Theseus"]}
      ]
    }
    /* more categories (science, history, geography, sport, music, film, ...) added in later batches */
  };

  // ---- helper ----
  var TB = {
    v: 4,
    bank: function(cat){ return TB_BANK[cat] || {}; },
    tiers: function(cat){ var b=TB_BANK[cat]||{}; return Object.keys(b); },
    count: function(cat){ var n=0, cats=cat?[cat]:Object.keys(TB_BANK);
      cats.forEach(function(c){ var b=TB_BANK[c]||{}; Object.keys(b).forEach(function(t){ n+=b[t].length; }); }); return n; },
    // optional convenience: a random question for a category+tier, avoiding ids in `seen`
    pick: function(cat, tier, seen){ var arr=(TB_BANK[cat]||{})[String(tier)]||[]; if(!arr.length) return null;
      seen=seen||{}; var ids=[]; for(var i=0;i<arr.length;i++){ if(!seen[cat+tier+':'+i]) ids.push(i); }
      if(!ids.length){ for(var j=0;j<arr.length;j++) ids.push(j); }
      var k=ids[Math.floor(Math.random()*ids.length)]; seen[cat+tier+':'+k]=1; return arr[k]; }
  };

  window.TB_BANK = TB_BANK;
  window.TB = TB;
})();
