/* ============================================================
   TierBrain — shared question repository
   ------------------------------------------------------------
   This file is NOT a page. It is a data library loaded by the
   games via:  <script src="questions.js?v=1"></script>
   Bump the ?v= number whenever you update this file so phones
   fetch the fresh copy instead of a cached one.

   Structure:  TB_BANK[category][tier] = [ {q, correct, wrong:[3]}, ... ]
     - category : "gk" (general knowledge), plus topic banks later
     - tier     : "1" easiest  ->  "4" hardest (matches game levels)

   Use in a game:   var BANK = TB.bank('gk');   // {1:[...],2:[...],3:[...],4:[...]}
   then keep the game's existing question-picking logic.

   CONTENT RULES (keep the bank trustworthy):
     - timeless, verifiable facts only; no current office-holders,
       "latest/biggest", or live records that go stale
     - no disputed answers unless the question is qualified
     - 3 wrong options that are clearly wrong but plausible
   ============================================================ */
(function(){
  var TB_BANK = {
    gk: {
      "1": [
        {q:"How many legs does an insect have?", correct:"Six", wrong:["Four", "Eight", "Ten"]},
        {q:"What is the opposite of 'up'?", correct:"Down", wrong:["Left", "Over", "Around"]},
        {q:"Which fruit is traditionally said to keep the doctor away?", correct:"Apple", wrong:["Banana", "Orange", "Grape"]},
        {q:"What do you call a baby dog?", correct:"Puppy", wrong:["Kitten", "Calf", "Cub"]},
        {q:"How many cents are there in a US dollar?", correct:"100", wrong:["50", "10", "1000"]},
        {q:"Which animal says 'moo'?", correct:"Cow", wrong:["Sheep", "Pig", "Duck"]},
        {q:"How many minutes are there in an hour?", correct:"60", wrong:["30", "100", "24"]},
        {q:"Which is the largest of these numbers: 5, 50 or 500?", correct:"500", wrong:["5", "50", "They are equal"]},
        {q:"What do plants mainly need from the Sun in order to grow?", correct:"Light", wrong:["Sound", "Salt", "Sugar"]},
        {q:"Which of these animals can fly?", correct:"Eagle", wrong:["Penguin", "Ostrich", "Salmon"]},
        {q:"What colour is grass?", correct:"Green", wrong:["Blue", "Red", "Purple"]},
        {q:"How many fingers are on one hand, including the thumb?", correct:"Five", wrong:["Four", "Six", "Ten"]},
        {q:"What do we call the meal usually eaten in the morning?", correct:"Breakfast", wrong:["Dinner", "Supper", "Lunch"]},
        {q:"What do you call a person who teaches pupils at school?", correct:"Teacher", wrong:["Doctor", "Farmer", "Pilot"]},
        {q:"What shape has four equal straight sides?", correct:"Square", wrong:["Triangle", "Circle", "Oval"]},
        {q:"What do bees make?", correct:"Honey", wrong:["Milk", "Silk", "Butter"]},
        {q:"What is the young of a cat called?", correct:"Kitten", wrong:["Puppy", "Foal", "Chick"]},
        {q:"How many sides does a square have?", correct:"Four", wrong:["Three", "Five", "Six"]},
        {q:"Which of these would help you see in the dark?", correct:"A torch", wrong:["A spoon", "A pillow", "A book"]},
        {q:"Which of these is a colour?", correct:"Red", wrong:["Loud", "Fast", "Tall"]},
        {q:"What do you call water that falls from the clouds?", correct:"Rain", wrong:["Sand", "Smoke", "Dust"]},
        {q:"How many eyes does a typical person have?", correct:"Two", wrong:["One", "Three", "Four"]},
        {q:"What is 2 + 2?", correct:"4", wrong:["3", "5", "22"]},
        {q:"Which animal has a long trunk?", correct:"Elephant", wrong:["Lion", "Zebra", "Bear"]},
        {q:"What day comes immediately after Monday?", correct:"Tuesday", wrong:["Sunday", "Wednesday", "Friday"]},
        {q:"What is the capital of France?", correct:"Paris", wrong:["Lyon","Marseille","Nice"]},
        {q:"How many legs does a spider have?", correct:"Eight", wrong:["Six","Ten","Four"]},
        {q:"What colour do you get by mixing blue and yellow?", correct:"Green", wrong:["Purple","Orange","Brown"]},
        {q:"Which planet do we live on?", correct:"Earth", wrong:["Mars","Venus","Jupiter"]},
        {q:"How many days are there in a week?", correct:"Seven", wrong:["Five","Six","Eight"]},
        {q:"What is H2O more commonly known as?", correct:"Water", wrong:["Salt","Oxygen","Vinegar"]},
        {q:"What is the largest land animal?", correct:"African elephant", wrong:["Hippopotamus","Giraffe","Rhinoceros"]},
        {q:"How many sides does a triangle have?", correct:"Three", wrong:["Four","Five","Two"]},
        {q:"What is the opposite of 'hot'?", correct:"Cold", wrong:["Warm","Dry","Wet"]},
        {q:"Which animal is often called 'man's best friend'?", correct:"Dog", wrong:["Cat","Horse","Rabbit"]},
        {q:"What gas do humans breathe in to survive?", correct:"Oxygen", wrong:["Carbon dioxide","Helium","Hydrogen"]},
        {q:"What is frozen water called?", correct:"Ice", wrong:["Steam","Mist","Fog"]},
        {q:"How many colours are traditionally said to be in a rainbow?", correct:"Seven", wrong:["Five","Six","Nine"]},
        {q:"What is the name of the star at the centre of our solar system?", correct:"The Sun", wrong:["The Moon","Polaris","Mars"]},
        {q:"Which is the tallest living animal in the world?", correct:"Giraffe", wrong:["Elephant","Horse","Camel"]},
        {q:"What do caterpillars turn into?", correct:"Butterflies", wrong:["Spiders","Bees","Beetles"]},
        {q:"What is the first letter of the English alphabet?", correct:"A", wrong:["Z","B","E"]},
        {q:"How many hours are there in a day?", correct:"24", wrong:["12","36","48"]},
        {q:"What colour is a ripe banana?", correct:"Yellow", wrong:["Blue","Purple","Red"]},
        {q:"Which season comes after winter?", correct:"Spring", wrong:["Summer","Autumn","Monsoon"]},
        {q:"What is the capital of England?", correct:"London", wrong:["Manchester","Birmingham","Liverpool"]},
        {q:"How many wheels does a standard bicycle have?", correct:"Two", wrong:["Three","Four","One"]},
        {q:"What do cows produce that people drink?", correct:"Milk", wrong:["Juice","Honey","Cider"]},
        {q:"Which of these is a fruit?", correct:"Apple", wrong:["Carrot","Potato","Onion"]},
        {q:"What is the colour of the sky on a clear day?", correct:"Blue", wrong:["Green","Pink","Grey"]}
      ],
      "2": [
        {q:"What is the capital of Italy?", correct:"Rome", wrong:["Milan", "Venice", "Naples"]},
        {q:"Who wrote 'A Christmas Carol'?", correct:"Charles Dickens", wrong:["Jane Austen", "Lewis Carroll", "Thomas Hardy"]},
        {q:"What is the chemical symbol for oxygen?", correct:"O", wrong:["Ox", "Og", "Om"]},
        {q:"How many sides does a hexagon have?", correct:"Six", wrong:["Five", "Seven", "Eight"]},
        {q:"Which is the smallest planet in our solar system?", correct:"Mercury", wrong:["Mars", "Venus", "Pluto"]},
        {q:"What is the capital of Germany?", correct:"Berlin", wrong:["Munich", "Hamburg", "Frankfurt"]},
        {q:"In which country are the Pyramids of Giza?", correct:"Egypt", wrong:["Mexico", "Greece", "Sudan"]},
        {q:"What is the currency of the United Kingdom?", correct:"Pound sterling", wrong:["Euro", "Dollar", "Franc"]},
        {q:"Who proposed the theory of evolution by natural selection?", correct:"Charles Darwin", wrong:["Gregor Mendel", "Louis Pasteur", "Carl Linnaeus"]},
        {q:"What is the largest country in the world by area?", correct:"Russia", wrong:["Canada", "China", "United States"]},
        {q:"Which gas do plants absorb from the air for photosynthesis?", correct:"Carbon dioxide", wrong:["Oxygen", "Nitrogen", "Hydrogen"]},
        {q:"What is the highest mountain above sea level on Earth?", correct:"Mount Everest", wrong:["K2", "Mont Blanc", "Kilimanjaro"]},
        {q:"How many bones are there in the adult human body?", correct:"206", wrong:["201", "212", "198"]},
        {q:"What is the capital of Russia?", correct:"Moscow", wrong:["Saint Petersburg", "Kazan", "Minsk"]},
        {q:"Which ocean lies between Africa and Australia?", correct:"Indian Ocean", wrong:["Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"]},
        {q:"What is the boiling point of water at sea level in degrees Celsius?", correct:"100", wrong:["90", "120", "50"]},
        {q:"Who wrote 'The Adventures of Tom Sawyer'?", correct:"Mark Twain", wrong:["Ernest Hemingway", "Jack London", "F. Scott Fitzgerald"]},
        {q:"What is the largest organ of the human body?", correct:"Skin", wrong:["Liver", "Brain", "Lungs"]},
        {q:"How many strings does a standard violin have?", correct:"Four", wrong:["Six", "Five", "Three"]},
        {q:"What is the capital of the United States?", correct:"Washington, D.C.", wrong:["New York City", "Los Angeles", "Chicago"]},
        {q:"Which metal is the best conductor of electricity?", correct:"Silver", wrong:["Copper", "Gold", "Iron"]},
        {q:"Who developed the first widely used polio vaccine in the 1950s?", correct:"Jonas Salk", wrong:["Alexander Fleming", "Edward Jenner", "Robert Koch"]},
        {q:"Which planet is famous for its prominent ring system?", correct:"Saturn", wrong:["Jupiter", "Mars", "Mercury"]},
        {q:"What is the chemical symbol for carbon?", correct:"C", wrong:["Ca", "Co", "Cr"]},
        {q:"How many players from one team are on a basketball court at once?", correct:"Five", wrong:["Six", "Seven", "Four"]},
        {q:"What is the capital of Australia?", correct:"Canberra", wrong:["Sydney","Melbourne","Perth"]},
        {q:"Who wrote the play 'Romeo and Juliet'?", correct:"William Shakespeare", wrong:["Charles Dickens","Jane Austen","Mark Twain"]},
        {q:"What is the chemical symbol for gold?", correct:"Au", wrong:["Gd","Go","Ag"]},
        {q:"How many players from one team are on the pitch in football (soccer)?", correct:"Eleven", wrong:["Ten","Nine","Twelve"]},
        {q:"What is the largest planet in our solar system?", correct:"Jupiter", wrong:["Saturn","Neptune","Earth"]},
        {q:"Which is the largest ocean on Earth?", correct:"Pacific", wrong:["Atlantic","Indian","Arctic"]},
        {q:"What currency is used in Japan?", correct:"Yen", wrong:["Won","Yuan","Ringgit"]},
        {q:"Who painted the Mona Lisa?", correct:"Leonardo da Vinci", wrong:["Michelangelo","Raphael","Donatello"]},
        {q:"What is the hardest known natural substance?", correct:"Diamond", wrong:["Granite","Iron","Quartz"]},
        {q:"How many continents are there on Earth?", correct:"Seven", wrong:["Five","Six","Eight"]},
        {q:"What is the chemical symbol for iron?", correct:"Fe", wrong:["Ir","In","Fr"]},
        {q:"Which gas makes up most of Earth's atmosphere?", correct:"Nitrogen", wrong:["Oxygen","Carbon dioxide","Hydrogen"]},
        {q:"In which country is the Eiffel Tower?", correct:"France", wrong:["Italy","Spain","Belgium"]},
        {q:"What is the smallest prime number?", correct:"2", wrong:["1","3","0"]},
        {q:"Who is the author of the 'Harry Potter' book series?", correct:"J.K. Rowling", wrong:["Roald Dahl","C.S. Lewis","Philip Pullman"]},
        {q:"What is the capital of Canada?", correct:"Ottawa", wrong:["Toronto","Vancouver","Montreal"]},
        {q:"How many strings does a standard guitar have?", correct:"Six", wrong:["Four","Five","Seven"]},
        {q:"What is the freezing point of water in degrees Celsius?", correct:"0", wrong:["32","100","-10"]},
        {q:"Which planet is known as the Red Planet?", correct:"Mars", wrong:["Venus","Mercury","Jupiter"]},
        {q:"What is the official language of Brazil?", correct:"Portuguese", wrong:["Spanish","Brazilian","French"]},
        {q:"Who developed the theory of general relativity?", correct:"Albert Einstein", wrong:["Isaac Newton","Galileo Galilei","Niels Bohr"]},
        {q:"What is the largest mammal in the world?", correct:"Blue whale", wrong:["African elephant","Giraffe","Orca"]},
        {q:"In which sport would you perform a 'slam dunk'?", correct:"Basketball", wrong:["Volleyball","Tennis","Cricket"]},
        {q:"What is the capital of Spain?", correct:"Madrid", wrong:["Barcelona","Seville","Valencia"]},
        {q:"How many minutes are there in a full day?", correct:"1440", wrong:["1240","960","1800"]}
      ],
      "3": [
        {q:"What is the capital of Greece?", correct:"Athens", wrong:["Thessaloniki", "Sparta", "Corinth"]},
        {q:"Who wrote 'Pride and Prejudice'?", correct:"Jane Austen", wrong:["Charlotte Bronte", "Emily Bronte", "George Eliot"]},
        {q:"What is the SI unit of force?", correct:"Newton", wrong:["Joule", "Pascal", "Watt"]},
        {q:"Which element has the chemical symbol 'Cu'?", correct:"Copper", wrong:["Calcium", "Cobalt", "Chromium"]},
        {q:"Who wrote the play 'A Doll's House'?", correct:"Henrik Ibsen", wrong:["Anton Chekhov", "August Strindberg", "Oscar Wilde"]},
        {q:"What is the name of the giant storm on Jupiter?", correct:"The Great Red Spot", wrong:["The Cassini Division", "The Great Dark Spot", "Olympus Mons"]},
        {q:"In what year did the Titanic sink?", correct:"1912", wrong:["1905", "1918", "1920"]},
        {q:"What is the capital of Portugal?", correct:"Lisbon", wrong:["Porto", "Coimbra", "Faro"]},
        {q:"What is the chemical formula for common table salt?", correct:"NaCl", wrong:["KCl", "NaCO", "Na2O"]},
        {q:"Who painted 'Guernica'?", correct:"Pablo Picasso", wrong:["Salvador Dali", "Joan Miro", "Francisco Goya"]},
        {q:"Which planet has the hottest surface in our solar system?", correct:"Venus", wrong:["Mercury", "Mars", "Jupiter"]},
        {q:"What is the scientific study of living organisms called?", correct:"Biology", wrong:["Geology", "Chemistry", "Physics"]},
        {q:"Which ancient Greek philosopher tutored Alexander the Great?", correct:"Aristotle", wrong:["Plato", "Socrates", "Pythagoras"]},
        {q:"What is the capital of Sweden?", correct:"Stockholm", wrong:["Gothenburg", "Malmo", "Helsinki"]},
        {q:"Which blood type is known as the universal donor?", correct:"O negative", wrong:["AB positive", "A positive", "B negative"]},
        {q:"Who wrote the novel 'Moby-Dick'?", correct:"Herman Melville", wrong:["Nathaniel Hawthorne", "Edgar Allan Poe", "Walt Whitman"]},
        {q:"What is the smallest unit of an element that keeps its properties?", correct:"Atom", wrong:["Molecule", "Cell", "Proton"]},
        {q:"In Roman numerals, what number does 'L' represent?", correct:"50", wrong:["100", "500", "5"]},
        {q:"What is the capital of Ireland?", correct:"Dublin", wrong:["Belfast", "Cork", "Galway"]},
        {q:"Which scientist is traditionally said to have been inspired by a falling apple?", correct:"Isaac Newton", wrong:["Galileo Galilei", "Albert Einstein", "Robert Hooke"]},
        {q:"What is the chemical symbol for silver?", correct:"Ag", wrong:["Si", "Sv", "Sl"]},
        {q:"Which sea lies between Europe and Africa, narrowest at the Strait of Gibraltar?", correct:"Mediterranean Sea", wrong:["Black Sea", "Red Sea", "Caspian Sea"]},
        {q:"Who wrote 'The Old Man and the Sea'?", correct:"Ernest Hemingway", wrong:["John Steinbeck", "William Faulkner", "F. Scott Fitzgerald"]},
        {q:"Which part of a cell is often called its 'powerhouse'?", correct:"Mitochondria", wrong:["Nucleus", "Ribosome", "Golgi apparatus"]},
        {q:"Which country gave the Statue of Liberty to the United States?", correct:"France", wrong:["United Kingdom", "Spain", "Italy"]},
        {q:"What is the SI unit of electrical resistance?", correct:"Ohm", wrong:["Volt","Ampere","Watt"]},
        {q:"Who wrote the novel 'Crime and Punishment'?", correct:"Fyodor Dostoevsky", wrong:["Leo Tolstoy","Anton Chekhov","Ivan Turgenev"]},
        {q:"What is the capital of New Zealand?", correct:"Wellington", wrong:["Auckland","Christchurch","Hamilton"]},
        {q:"Which element has the atomic number 1?", correct:"Hydrogen", wrong:["Helium","Oxygen","Carbon"]},
        {q:"Who composed 'The Four Seasons'?", correct:"Antonio Vivaldi", wrong:["Johann Sebastian Bach","Wolfgang Amadeus Mozart","Ludwig van Beethoven"]},
        {q:"What is the world's largest hot desert?", correct:"Sahara", wrong:["Gobi","Kalahari","Arabian"]},
        {q:"In Greek mythology, who is the king of the gods?", correct:"Zeus", wrong:["Poseidon","Hades","Apollo"]},
        {q:"What is the chemical symbol for sodium?", correct:"Na", wrong:["So","Sd","S"]},
        {q:"Which artist famously cut off part of his own ear?", correct:"Vincent van Gogh", wrong:["Pablo Picasso","Claude Monet","Salvador Dali"]},
        {q:"Which organ in the human body produces insulin?", correct:"Pancreas", wrong:["Liver","Kidney","Spleen"]},
        {q:"Who was the first person to walk on the Moon?", correct:"Neil Armstrong", wrong:["Buzz Aldrin","Yuri Gagarin","Michael Collins"]},
        {q:"What is the capital of Egypt?", correct:"Cairo", wrong:["Alexandria","Giza","Luxor"]},
        {q:"In which Shakespeare play does the character Iago appear?", correct:"Othello", wrong:["Hamlet","Macbeth","King Lear"]},
        {q:"The speed of light in a vacuum is approximately how fast?", correct:"300,000 km/s", wrong:["150,000 km/s","30,000 km/s","3,000 km/s"]},
        {q:"Who composed the music for the ballet 'Swan Lake'?", correct:"Pyotr Ilyich Tchaikovsky", wrong:["Igor Stravinsky","Sergei Prokofiev","Claude Debussy"]},
        {q:"What is the largest internal organ in the human body?", correct:"Liver", wrong:["Stomach","Lungs","Brain"]},
        {q:"Which metal is liquid at room temperature?", correct:"Mercury", wrong:["Lead","Aluminium","Zinc"]},
        {q:"What is the capital of Norway?", correct:"Oslo", wrong:["Bergen","Stavanger","Trondheim"]},
        {q:"Who painted 'The Persistence of Memory', known for its melting clocks?", correct:"Salvador Dali", wrong:["Pablo Picasso","Joan Miro","Rene Magritte"]},
        {q:"What is the longest bone in the human body?", correct:"Femur", wrong:["Tibia","Humerus","Fibula"]},
        {q:"In which year did World War II end?", correct:"1945", wrong:["1944","1946","1939"]},
        {q:"What is the chemical symbol for potassium?", correct:"K", wrong:["P","Po","Pt"]},
        {q:"Which planet is closest to the Sun?", correct:"Mercury", wrong:["Venus","Earth","Mars"]},
        {q:"Who wrote the novels '1984' and 'Animal Farm'?", correct:"George Orwell", wrong:["Aldous Huxley","Ray Bradbury","H.G. Wells"]},
        {q:"What is the scientific study of weather called?", correct:"Meteorology", wrong:["Geology","Astrology","Ecology"]}
      ],
      "4": [
        {q:"Who wrote 'One Hundred Years of Solitude'?", correct:"Gabriel Garcia Marquez", wrong:["Jorge Luis Borges", "Mario Vargas Llosa", "Pablo Neruda"]},
        {q:"What is the chemical symbol for the element mercury?", correct:"Hg", wrong:["Mc", "Me", "Mg"]},
        {q:"Which ancient Greek is known as the 'father of geometry'?", correct:"Euclid", wrong:["Pythagoras", "Archimedes", "Thales"]},
        {q:"What is the capital of Finland?", correct:"Helsinki", wrong:["Stockholm", "Oslo", "Tallinn"]},
        {q:"Who composed 'The Rite of Spring'?", correct:"Igor Stravinsky", wrong:["Claude Debussy", "Maurice Ravel", "Sergei Rachmaninoff"]},
        {q:"What is the most abundant metal in the Earth's crust?", correct:"Aluminium", wrong:["Iron", "Copper", "Magnesium"]},
        {q:"Who painted 'The Night Watch'?", correct:"Rembrandt", wrong:["Johannes Vermeer", "Peter Paul Rubens", "Frans Hals"]},
        {q:"What is the term for an animal that eats only plants?", correct:"Herbivore", wrong:["Carnivore", "Omnivore", "Insectivore"]},
        {q:"Which civilization built the mountain city of Machu Picchu?", correct:"The Inca", wrong:["The Aztec", "The Maya", "The Olmec"]},
        {q:"What is the chemical symbol for tin?", correct:"Sn", wrong:["Ti", "Tn", "Te"]},
        {q:"Who wrote the dystopian novel 'Brave New World'?", correct:"Aldous Huxley", wrong:["George Orwell", "Ray Bradbury", "Yevgeny Zamyatin"]},
        {q:"What is the SI unit of frequency?", correct:"Hertz", wrong:["Decibel", "Joule", "Pascal"]},
        {q:"Which lake is so salty that swimmers float easily in it?", correct:"The Dead Sea", wrong:["The Red Sea", "The Caspian Sea", "Lake Victoria"]},
        {q:"Who founded the practice of psychoanalysis?", correct:"Sigmund Freud", wrong:["Carl Jung", "Ivan Pavlov", "B.F. Skinner"]},
        {q:"What is the capital of Iceland?", correct:"Reykjavik", wrong:["Oslo", "Nuuk", "Bergen"]},
        {q:"Which element is represented by the symbol 'He'?", correct:"Helium", wrong:["Hydrogen", "Mercury", "Hafnium"]},
        {q:"Who wrote the two-part tragedy 'Faust'?", correct:"Johann Wolfgang von Goethe", wrong:["Friedrich Schiller", "Heinrich Heine", "Thomas Mann"]},
        {q:"What is the hardest substance produced by the human body?", correct:"Tooth enamel", wrong:["Bone", "Cartilage", "Fingernail"]},
        {q:"Who composed the 'Brandenburg Concertos'?", correct:"Johann Sebastian Bach", wrong:["George Frideric Handel", "Antonio Vivaldi", "Henry Purcell"]},
        {q:"What is the largest moon of the planet Saturn?", correct:"Titan", wrong:["Europa", "Ganymede", "Triton"]},
        {q:"Who wrote 'The Canterbury Tales'?", correct:"Geoffrey Chaucer", wrong:["William Langland", "Thomas Malory", "John Gower"]},
        {q:"Which gas, with the formula O3, forms a protective layer in the stratosphere?", correct:"Ozone", wrong:["Carbon monoxide", "Methane", "Argon"]},
        {q:"What is the capital of Morocco?", correct:"Rabat", wrong:["Casablanca", "Marrakech", "Fez"]},
        {q:"Who painted 'The Birth of Venus'?", correct:"Sandro Botticelli", wrong:["Titian", "Raphael", "Caravaggio"]},
        {q:"In physics, the letter 'c' most commonly represents what?", correct:"The speed of light", wrong:["Acceleration", "Mass", "Electric charge"]},
        {q:"Who proposed the uncertainty principle in quantum mechanics?", correct:"Werner Heisenberg", wrong:["Erwin Schrodinger","Max Planck","Paul Dirac"]},
        {q:"What is the capital of Bhutan?", correct:"Thimphu", wrong:["Kathmandu","Dhaka","Naypyidaw"]},
        {q:"Which Russian author wrote 'War and Peace'?", correct:"Leo Tolstoy", wrong:["Fyodor Dostoevsky","Boris Pasternak","Maxim Gorky"]},
        {q:"What is the chemical symbol for tungsten?", correct:"W", wrong:["Tu","Tn","Tg"]},
        {q:"In what year did the Berlin Wall fall?", correct:"1989", wrong:["1987","1991","1985"]},
        {q:"Who composed the opera 'The Marriage of Figaro'?", correct:"Wolfgang Amadeus Mozart", wrong:["Giuseppe Verdi","Richard Wagner","Giacomo Puccini"]},
        {q:"What is the smallest country in the world by area?", correct:"Vatican City", wrong:["Monaco","San Marino","Liechtenstein"]},
        {q:"Which scientist formulated the three laws of planetary motion?", correct:"Johannes Kepler", wrong:["Tycho Brahe","Galileo Galilei","Nicolaus Copernicus"]},
        {q:"Which mineral sits at the top (10) of the Mohs hardness scale?", correct:"Diamond", wrong:["Corundum","Topaz","Quartz"]},
        {q:"Who wrote the philosophical work 'Critique of Pure Reason'?", correct:"Immanuel Kant", wrong:["Friedrich Nietzsche","Georg Hegel","Arthur Schopenhauer"]},
        {q:"What is the capital of Mongolia?", correct:"Ulaanbaatar", wrong:["Astana","Bishkek","Tashkent"]},
        {q:"Which metal has the highest melting point?", correct:"Tungsten", wrong:["Iron","Platinum","Titanium"]},
        {q:"Who painted the ceiling of the Sistine Chapel?", correct:"Michelangelo", wrong:["Leonardo da Vinci","Raphael","Caravaggio"]},
        {q:"What is the longest river in South America?", correct:"Amazon", wrong:["Parana","Orinoco","Sao Francisco"]},
        {q:"Which mathematician is known for his 'Last Theorem'?", correct:"Pierre de Fermat", wrong:["Carl Gauss","Leonhard Euler","Blaise Pascal"]},
        {q:"What is the chemical symbol for lead?", correct:"Pb", wrong:["Ld","Le","Pl"]},
        {q:"Which Ancient Wonder stood in the harbour of Rhodes?", correct:"The Colossus of Rhodes", wrong:["The Hanging Gardens","The Lighthouse of Alexandria","The Temple of Artemis"]},
        {q:"Who wrote the epic poem 'The Divine Comedy'?", correct:"Dante Alighieri", wrong:["Petrarch","Giovanni Boccaccio","Virgil"]},
        {q:"What is the SI base unit of luminous intensity?", correct:"Candela", wrong:["Lumen","Lux","Watt"]},
        {q:"Which composer kept composing after becoming profoundly deaf?", correct:"Ludwig van Beethoven", wrong:["Franz Schubert","Johannes Brahms","Frederic Chopin"]},
        {q:"Which planet in our solar system rotates roughly on its side?", correct:"Uranus", wrong:["Neptune","Saturn","Venus"]},
        {q:"Who is credited with discovering penicillin?", correct:"Alexander Fleming", wrong:["Louis Pasteur","Joseph Lister","Robert Koch"]},
        {q:"What is the term for a word that reads the same forwards and backwards?", correct:"Palindrome", wrong:["Anagram","Homonym","Onomatopoeia"]},
        {q:"Which element is the most abundant in the Sun?", correct:"Hydrogen", wrong:["Helium","Oxygen","Carbon"]},
        {q:"In Greek mythology, who flew too close to the Sun on wax wings?", correct:"Icarus", wrong:["Daedalus","Perseus","Theseus"]}
      ]
    }
    /* more categories (science, history, geography, sport, music, film, ...) added in later batches */
  };

  // ---- helper ----
  var TB = {
    v: 2,
    bank: function(cat){ return TB_BANK[cat] || {}; },
    tiers: function(cat){ var b=TB_BANK[cat]||{}; return Object.keys(b); },
    count: function(cat){ var n=0, cats=cat?[cat]:Object.keys(TB_BANK);
      cats.forEach(function(c){ var b=TB_BANK[c]||{}; Object.keys(b).forEach(function(t){ n+=b[t].length; }); }); return n; },
    // optional convenience: a random question for a category+tier, avoiding ids in `seen`
    pick: function(cat, tier, seen){ var arr=(TB_BANK[cat]||{})[String(tier)]||[]; if(!arr.length) return null;
      seen=seen||{}; var ids=[]; for(var i=0;i<arr.length;i++){ if(!seen[cat+tier+':'+i]) ids.push(i); }
      if(!ids.length){ for(var j=0;j<arr.length;j++) ids.push(j); }
      var k=ids[Math.floor(Math.random()*ids.length)]; seen[cat+tier+':'+k]=1; return arr[k]; }
  };

  window.TB_BANK = TB_BANK;
  window.TB = TB;
})();
